DROP TABLE IF EXISTS people;

CREATE TABLE people
(
    id BIGINT(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    age INTEGER(3) NOT NULL,
    email VARCHAR(255) NOT NULL
);